repos:
  - repo: local
    hooks:
    -   id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]

    -   id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]

    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

exclude: 'README.md'
